//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Training_Calendar
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Tbl_Entities : DbContext
    {
        public Tbl_Entities()
            : base("name=Tbl_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Behavioral_Trainings> Tbl_Behavioral_Trainings { get; set; }
        public virtual DbSet<Tbl_Technical_Trainings> Tbl_Technical_Trainings { get; set; }
    }
}
